version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: "@babel/*"
    versions:
    - ">= 0"
  - dependency-name: core-js
    versions:
    - ">= 0"
  - dependency-name: "@date-io/*"
    versions:
    - ">= 0"
  - dependency-name: jss-*
    versions:
    - ">= 0"
  - dependency-name: raw-loader
    versions:
    - ">= 0"
  - dependency-name: react-dom
    versions:
    - ">= 0"
  - dependency-name: react-is
    versions:
    - ">= 0"
  - dependency-name: react-test-renderer
    versions:
    - ">= 0"
  - dependency-name: tslint
    versions:
    - 5.x
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - ">= 0"
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: framer-motion
    versions:
    - 3.2.1
    - 3.6.2
  - dependency-name: aws-sdk
    versions:
    - 2.828.0
    - 2.848.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.13.0
    - 4.15.1
  - dependency-name: "@types/luxon"
    versions:
    - 1.25.1
    - 1.25.2
  - dependency-name: "@chakra-ui/system"
    versions:
    - 1.1.6
    - 1.3.1
  - dependency-name: marked
    versions:
    - 2.0.0
  - dependency-name: autoprefixer
    versions:
    - 10.2.1
    - 10.2.4
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: "@testing-library/react-hooks"
    versions:
    - 5.0.0
  - dependency-name: "@testing-library/dom"
    versions:
    - 7.29.4
